NVCC=nvcc

EXECUTABLES=aes_ecb_e aes_ecb_d
OBJECTS=AES.o main_ecb_e.o main_ecb_d.o
AES_FILES=AES.cu AES.h AES.tab BlockCipher.h

all: $(EXECUTABLES)

aes_ecb_e: AES.o main_ecb_e.o
	$(NVCC) -o $@ $^

aes_ecb_d: AES.o main_ecb_d.o
	$(NVCC) -o $@ $^

AES.o: $(AES_FILES)
	$(NVCC) -c -o $@ $<

main_ecb_e.o: main_ecb_e.cu main.h
	$(NVCC) -c -o $@ $<

main_ecb_d.o: main_ecb_d.cu main.h
	$(NVCC) -c -o $@ $<

clean:
	$(RM) $(EXECUTABLES) $(OBJECTS)
